apiVersion: v1
kind: Service
metadata:
  name: kube-action-service
  labels: 
    group: example
spec:
  selector:
    app: kube-action-pod
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-action-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-action-pod
  template:
    metadata:
      labels:
        app: kube-action-pod
    spec:
      containers:
      - name: kube-action-node
        image: jhapranav/kube-action
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # ports:
        # - containerPort: <Port>


